#!/usr/bin/env bash
read -p 'Use Ninja [yN]: ' NINJA
NINJA=${NINJA:n}
case $NINJA in
	Y|y)
		echo "Using Ninja"
		GENERATOR='-G "Ninja"'
		;;
	N|n|*)
		echo "Using Unix Makefiles"
		GENERATOR='-G "Unix Makefiles"'
		;;
esac

read -p 'Use Clang [yN]: ' CLANG
CLANG=${CLANG:n}
case $CLANG in
	Y|y)
		echo "Using Clang"
		COMPILER='-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'
		;;
	N|n|*)
		echo "Using GCC"
		COMPILER='-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++'
		;;
esac

if [ -d build ]; then
	set -x
	rm -rf build
fi
set -x
mkdir build && cd build
eval cmake ${GENERATOR} ${COMPILER} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "$@" ..
