#!/usr/bin/env bash

# Build Type
read -p 'Use Debug Build Type [Yn]: ' DEBUG
case ${DEBUG:-y} in
	N|n)
		echo "Build Type: Release"
		BUILD_TYPE='-DCMAKE_BUILD_TYPE=Release'
		;;
	Y|y|*)
		echo "Build Type: Debug"
		BUILD_TYPE='-DCMAKE_BUILD_TYPE=Debug'
		;;
esac

# Generator
read -p 'Use Unix Makefiles Generator [Yn]: ' MAKEFILES
case ${MAKEFILES:-y} in
	N|n)
		echo "Generator: Ninja"
		GENERATOR='-G "Ninja"'
		;;
	Y|y|*)
		echo "Generator: Unix Makefiles"
		GENERATOR='-G "Unix Makefiles"'
		;;
esac

# Compiler
read -p 'Use GCC Compiler [Yn]: ' GCC
case ${GCC:-y} in
	N|n)
		echo "Compiler: Clang"
		COMPILER='-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'
		;;
	Y|y|*)
		echo "Compiler: GCC"
		COMPILER='-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++'
		;;
esac

# Documentation
read -p 'Enable Documentation [Yn]: ' DOC
case ${DOC:-y} in
	N|n)
		echo "Documentation: Disable"
		DOCUMENTATION=''
		;;
	Y|y|*)
		echo "Documentation: Enable"
		DOCUMENTATION='-DENABLE_DOC=ON'
		;;
esac

# Coverage
read -p 'Enable Coverage [Yn]: ' DOC
case ${DOC:-y} in
	N|n)
		echo "Coverage: Disable"
		COVERAGE=''
		;;
	Y|y|*)
		echo "Coverage: Enable"
		COVERAGE='-DENABLE_GCOV=ON'
		;;
esac

if [ -d build ]; then
	rm -rf build
fi
mkdir build && cd build
eval cmake ${BUILD_TYPE} ${GENERATOR} ${COMPILER} ${DOCUMENTATION} ${COVERAGE} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "$@" ..
