#!/usr/bin/env bash

# Build Type
read -p 'Use Debug Build Type [Yn]: ' DEBUG
case ${DEBUG:-y} in
	N|n)
		echo "Build Type: Release"
		BUILD_TYPE='-DCMAKE_BUILD_TYPE=Release'
		;;
	Y|y|*)
		echo "Build Type: Debug"
		BUILD_TYPE='-DCMAKE_BUILD_TYPE=Debug'
		;;
esac

# Generator
read -p 'Use Unix Makefiles Generator [Yn]: ' MAKEFILES
case ${MAKEFILES:-y} in
	N|n)
		echo "Generator: Ninja"
		GENERATOR='-G "Ninja"'
		;;
	Y|y|*)
		echo "Generator: Unix Makefiles"
		GENERATOR='-G "Unix Makefiles"'
		;;
esac

# Compiler
read -p 'Use GCC Compiler [Yn]: ' GCC
case ${GCC:-y} in
	N|n)
		echo "Compiler: Clang"
		COMPILER='-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++'
		;;
	Y|y|*)
		echo "Compiler: GCC"
		COMPILER='-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++'
		;;
esac

if [ -d build ]; then
	rm -rf build
fi
set -x
mkdir build && cd build
eval cmake ${BUILD_TYPE} ${GENERATOR} ${COMPILER} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "$@" ..
