#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# use DRI_PRIME=1 cmd args...
xrandr --setprovideroffloadsink nouveau Intel

xsetroot -cursor_name left_ptr
setxkbmap fr

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

#xrandr --output eDP1 --auto --output HDMI1 --above eDP1 --auto
#xrandr --output eDP1 --auto --output HDMI1 --left-of eDP1 --auto

exec awesome
#exec xmonad
#exec gnome-session
#exec startkde
#exec startxfce4
#...or the Window Manager of your choice
