#theme = "doom_acario_dark"
#theme = "github_dark_high_contrast"
theme = "vim_dark_high_contrast"

[editor]
# Force the theme to show colors
true-color = true
color-modes = true
# Highlight all lines with a cursor
cursorline = true
# Use relative line numbers
#line-number = "relative"
# Show a ruler at column 80,120
rulers = [80,120]
# Show currently open buffers, only when more than one exists.
#bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
ignore = false
hidden = false

[editor.indent-guides]
character = "╎"
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"C-r" = [":config-reload"]
"C-o" = [":open ~/.config/helix/config.toml"]
"G" = ["goto_last_line"]
g = { a = "code_action" } # Maps `ga` to show possible code actions
"=" = [ ":format" ]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
