set nocompatible " be iMproved, required
set mouse=a " Use mouse in vim
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim' " let Vundle manage Vundle, required
Plugin 'Valloric/YouCompleteMe' " A code-completion engine
Plugin 'rdnetto/YCM-Generator' " Generate YCM file using :YcmGenerateConfig
"Plugin 'neoclide/coc.nvim' " Nodejs support
Plugin 'scrooloose/syntastic' " Syntax checking hacks
Plugin 'scrooloose/nerdtree' " Nerd Tree
"Plugin 'severin-lemaignan/vim-minimap' " Sublime minimap equivalent
Plugin 'majutsushi/tagbar' " displays tags in a window, ordered by scope
Plugin 'jlanzarotta/bufexplorer' " convenient buffer explorer
Plugin 'airblade/vim-gitgutter' " shows a git diff/stage/revert using sign column
Plugin 'bling/vim-airline' " lean & mean status/tabline
Plugin 'flazz/vim-colorschemes' " one colorscheme pack to rule them all!
call vundle#end() " required
filetype plugin indent on " required
" :PluginInstall - installs plugins; append `!` to update or just :PluginUpdate

colorscheme mouse | set background=dark | set guifont=DejaVu\ Sans\ Mono\ 10 | set termguicolors
set number | set ruler | set cursorline | set textwidth=80
syntax enable | set showmatch | set hlsearch | set hlsearch | set ignorecase | set smartcase
set autoindent | set smartindent | set tabstop=2 | set shiftwidth=2 | set softtabstop=2 | set expandtab
set foldmethod=syntax | set foldlevelstart=99 | set foldenable
let g:xml_syntax_folding=1
let g:sh_fold_enabled=5
set ssop-=options | set ssop-=folds

" Remove trailing whitespace
function! CleanWhiteSpace()
  " Don't strip on these filetypes
  if &ft =~ 'markdown\|perl\|diff'
    return
  endif
  let _s=@/
  let l = line(".")
  let c = col(".")
  :%s/\s\+$//e
  let @/=_s
  call cursor(l, c)
endfunction()
" Remove trailing whitespaces when saving:
autocmd bufwritepre * call CleanWhiteSpace()

nnoremap <silent> <c-e> :Explore<cr> " open built-in TreeExplorer
nnoremap <silent> <c-n> :NERDTreeToggle<cr> " open NerdTree
nnoremap <silent> <c-b> :BufExplorer<cr> " open BufExplorer
nnoremap <silent> <c-t> :TagbarToggle<cr> " open TagBar
"nnoremap <silent> <c-m> :MinimapToggle<cr> " open Minimap

" CTags Completion (C-F8 generate)
set tags=./tags;
map <C-F8> :!ctags -R --sort=yes --c++-kinds=+pl --fields=+iaS --extra=+q .<CR>
" NerdTree style
let g:netrw_liststyle=3
" load Doxygen syntax per default
au BufNewFile,BufRead *.dox set filetype=doxygen
let g:load_doxygen_syntax = 1
let g:doxygen_enhanced_colour = 0
let doxygen_my_rendering = 1
let doxygen_javadoc_autobrief = 0
let doxygen_end_punctuation = '[.]'
" SVG load xml syntax for indentation
au BufNewFile,BufRead *.svg set filetype=xml
" SWIG load swig syntax for indentation
au BufNewFile,BufRead *.i set filetype=swig
" .NET load xml syntax for indentation
au BufNewFile,BufRead *.fsproj set filetype=xml
