#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

xsetroot -cursor_name left_ptr
setxkbmap fr

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

#exe awesome
#exec xmonad
#exec gnome-session
#exec startkde
exec startxfce4
# ...or the Window Manager of your choice
