#!/bin/sh
# Executed by startx (run your window manager from here)
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Old Nvidia Setup
#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto

# use DRI_PRIME=1 cmd args...
xrandr --setprovideroffloadsink nouveau Intel

# merge in defaults and keymaps
if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xsetroot -cursor_name left_ptr
setxkbmap fr

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

#xrandr --output eDP1 --auto --output HDMI1 --above eDP1 --auto
#xrandr --output eDP1 --auto --output HDMI1 --left-of eDP1 --auto

exec awesome
#exec startxfce4
#exec gnome-session
#exec startkde

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
